### ISSUE TITLE
New Rotation Source too Fast and no default

### ISSUE THREAD

**Issue by Tanglewolf** [Allen-Wrench/NoForcedCameraZoom#5]
This update caught me by surprise, i thought all my ships were broken as the cameras are all over, lost a few hours investigating graphics 3d driver settings. Could a default not be set to the cockpit so its starts in a normal  position?

Iv found i cant reset the rotation source to the cockpit as the movement of the red dot is just too fast especially on small ships, would it be possible to slow them down?

Nice touch to a great little plug in though

**Comment by Allen-Wrench** [comment]
Sorry for the confusion! I'm actually going to work on a way to show a little update notification in the main menu for new updates. since people probably wont otherwise know when something changes unless they go into the plugin menu and check descriptions...

I'll have another update ready with a way to reset the offset, as well as a way to adjust the speed at which it moves, and toggles to hide the bounding box/red dot overlays, hopefully tonight or tomorrow.

**Comment by YoshiWoof22** [comment]
Glad to have found this post; I too was thrown for a loop and confused for around an hour trying to find out which plugn suddenly broke my third-person camera on every grid (it started underground on every single rover).

> I'll have another update ready with a way to reset the offset, as well as a way to adjust the speed at which it moves, and toggles to hide the bounding box/red dot overlays, hopefully tonight or tomorrow.

Thank you for trying to add this new functionality - I can see this being useful for certain grids, but for the majority of use cases I do prefer the old behaviour as it stands currently. If that reset option is consistent & adjustable so I can make it behave like prior to this update, that would be very much appreciated ^^

**Comment by Squeech007** [comment]
need to add option to fix the pivot. on my small ship its after reentering cockpit reset to a stupid off location. maybe due to using a merge block before.

**Comment by Allen-Wrench** [comment]
It was not my intention to affect anything other than grids where you specifically changed rotation point, so im pushing out a fix for that right now. Sorry about that guys, just got back from work and noticed my error.

**Comment by draconb** [comment]
> It was not my intention to affect anything other than grids where you specifically changed rotation point, so im pushing out a fix for that right now. Sorry about that guys, just got back from work and noticed my error.

Hey just loaded up and having the same issue as the others, not sure if the fix didn't get applied yet or its still broken by default.

**Comment by Allen-Wrench** [comment]
Update is submitted, just waiting approval. 
** New version you can reset the offset to default by pressing Numpad Zero while holding Ctrl + Shift. And adjusting the offset is now more like a bolt action rifle instead of a machine gun ;)

Sorry it took a bit longer than I hoped, silly me forgot to disable the plugin in the plugin loader while I was doing my testing. So I was going a bit crazy trying to figure out why none of my attempts to fix the bug were working. Turns out when the plugin loader loads the bugged plugin again after you already loaded your development version, things don't work as expected lmao.

**Comment by InfernoSuperNova** [comment]
This is something I didn't know I wanted. Totally caught me off guard though, and zeroing would definitely be ideal. Perhaps controlling it with WASD and moves relative to the camera too would be good?

**Comment by Squeech007** [comment]
Thank you for doing any of this in the first place! Your plugin is a number one must-have and one of the very first things i was looking for because the collision cam drove me crazy from day1!

**Comment by Allen-Wrench** [comment]
> This is something I didn't know I wanted. Totally caught me off guard though, and zeroing would definitely be ideal. Perhaps controlling it with WASD and moves relative to the camera too would be good?

I'm currently working on a configuration UI and I want to be able to allow people to set their own hotkeys, but I don't have any plans of making any sort of "spectator-esque" kind of movement to change the offset. I had though about it, but it seems a bit overkill.



> Thank you for doing any of this in the first place! Your plugin is a number one must-have and one of the very first things i was looking for because the collision cam drove me crazy from day1!

You are welcome! I felt the same way when I first started playing SE, it drove me nuts. So after I ended up teaching myself C# so I could write scripts, and then eventually got into writing plugins, this was something I had to do. I might have to update the name of it though since it has sort of evolved into more than just disabling the camera obstructions. 
You should check out my other plugins, Jump Selector was my first and probably my favorite :)

**Comment by Tanglewolf** [comment]
Thankyou, these adjustments sound brilliant. I like the idea of moving the rotation point, makes for some very interesting angles. This and definately jump selector are two of my favourite plugins

**Comment by Squeech007** [comment]
of course i use jump selector! i use all ur mods lol

**Comment by evilcommand** [comment]
> ** New version you can reset the offset to default by pressing Numpad Zero while holding Ctrl + Shift. And adjusting the offset is now more like a bolt action rifle instead of a machine gun 



this doesnt seem to work for me also i am playing on a Nexus Server and would be posible to save its location across server instances ?

**Comment by Allen-Wrench** [comment]
> > ** New version you can reset the offset to default by pressing Numpad Zero while holding Ctrl + Shift. And adjusting the offset is now more like a bolt action rifle instead of a machine gun
> 
> this doesnt seem to work for me also i am playing on a Nexus Server and would be posible to save its location across server instances ?

Yeah, the plugin had not been verified until just a few minutes ago, so...
### everything should work as intended now (crosses fingers). 

I actually had not taken Nexus into account, but I'll look into it. I can see how that would be annoying to have to re-adjust every time you switched instances.

**Comment by Allen-Wrench** [comment]
Plugin updated, all of these issues _should_ be fixed.

**Comment by YoshiWoof22** [comment]
Can confirm, positions have been reset on every grid I tried it with.

Thank you very much for the quick fix!
